# Import Dependencies

In [1]:
import pandas as pd
import pycountry
from sqlalchemy import create_engine
from getpass import getpass

# Starbucks Data -Dataset 1

In [2]:
starbucks_raw = "Resources\starbucks.csv"
starbucks_df = pd.read_csv(starbucks_raw)
starbucks_df.head()

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
0,Starbucks,47370-257954,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,AD,AD500,376818720,GMT+1:00 Europe/Andorra,1.53,42.51
1,Starbucks,47089-256771,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,55.47,25.39
2,Starbucks,22126-218024,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,54.38,24.48
3,Starbucks,17127-178586,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,54.54,24.51
4,Starbucks,17688-182164,"Dalma Mall, Ground Floor",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,54.49,24.40

# Clean Starbucks dataset

## Eliminate unnecessary columns

In [3]:
test_df = starbucks_df[['Store Number','Brand', 'Store Name','Ownership Type','Street Address','City','State/Province','Country']]
test_df.head()

,Store Number,Brand,Store Name,Ownership Type,Street Address,City,State/Province,Country
0,47370-257954,Starbucks,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,AD
1,47089-256771,Starbucks,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,AE
2,22126-218024,Starbucks,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,AE
3,17127-178586,Starbucks,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,AE
4,17688-182164,Starbucks,"Dalma Mall, Ground Floor",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,AE

In [4]:
# pycountry.countries.lookup('AD')

pycountry.countries.lookup(test_df['Country'][0])

Country(alpha_2='AD', alpha_3='AND', name='Andorra', numeric='020', official_name='Principality of Andorra')

In [5]:
pycountry.countries.get(alpha_2 = 'AD').name

'Andorra'

In [6]:
df = test_df

list_alpha_2 = [i.alpha_2 for i in list(pycountry.countries)]

def country_flag(df):
    if (len(df['Country'])==2 and df['Country'] in list_alpha_2):
        return pycountry.countries.get(alpha_2=df['Country']).name
    else:
        inv_count += 1
        return 'Invalid Code'

test_df['country_2']=test_df.apply(country_flag, axis = 1)

test_df.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

,Store Number,Brand,Store Name,Ownership Type,Street Address,City,State/Province,Country,country_2
0,47370-257954,Starbucks,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,AD,Andorra
1,47089-256771,Starbucks,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,AE,United Arab Emirates
2,22126-218024,Starbucks,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,AE,United Arab Emirates
3,17127-178586,Starbucks,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,AE,United Arab Emirates
4,17688-182164,Starbucks,"Dalma Mall, Ground Floor",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,AE,United Arab Emirates

In [7]:
starbucks_df = test_df[['Brand','Store Number', 'Store Name','Ownership Type','Street Address','City','State/Province','Country','country_2']].copy()
starbucks_df = starbucks_df.rename(columns={"Store Number":"id",
                                      "Brand":"brand",
                                      "Store Name":"store_name",
                                      "Ownership Type":"ownership_type",
                                      "Street Address":"address",
                                      "City":"city",
                                      "State/Province":"state",
                                      "country_2":"country"})

In [8]:
starbucks_df = starbucks_df[['id','brand', 'store_name','ownership_type','address','city','state','country']]
starbucks_df.set_index('id')

starbucks_df.head()
# starbucks_df = starbucks_df[starbucks_df['id']!='47370-257954']

,id,brand,store_name,ownership_type,address,city,state,country
0,47370-257954,Starbucks,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,Andorra
1,47089-256771,Starbucks,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,United Arab Emirates
2,22126-218024,Starbucks,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,United Arab Emirates
3,17127-178586,Starbucks,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,United Arab Emirates
4,17688-182164,Starbucks,"Dalma Mall, Ground Floor",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,United Arab Emirates

In [ ]:
#starbucks_df['country'].value_counts().nlargest()

In [9]:
starbucks_df[["id", "country"]].head()

             id               country
0  47370-257954               Andorra
1  47089-256771  United Arab Emirates
2  22126-218024  United Arab Emirates
3  17127-178586  United Arab Emirates
4  17688-182164  United Arab Emirates

# Check for Duplicate Values

In [10]:
starbucks_df[starbucks_df.duplicated(['id'], keep=False)]

Empty DataFrame
Columns: [id, brand, store_name, ownership_type, address, city, state, country]
Index: []

In [ ]:
# starbucks[starbucks.duplicated(['id'], keep='first')]

In [11]:
starbucks_df['country'].value_counts().nlargest()

United States         13608
China                  2734
Canada                 1468
Japan                  1237
Korea, Republic of      992
Name: country, dtype: int64

In [12]:
starbucks_df['id']=[i.replace('-','') for i in starbucks_df['id']]

starbucks_df.head()

,id,brand,store_name,ownership_type,address,city,state,country
0,47370257954,Starbucks,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,Andorra
1,47089256771,Starbucks,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,United Arab Emirates
2,22126218024,Starbucks,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,United Arab Emirates
3,17127178586,Starbucks,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,United Arab Emirates
4,17688182164,Starbucks,"Dalma Mall, Ground Floor",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,United Arab Emirates

# Country database

In [13]:
country_raw = pd.read_csv("Resources\world-happiness-report-2019.csv")
country_raw.head()

,Country (region),Ladder,SD of Ladder,Positive affect,Negative affect,Social support,Freedom,Corruption,Generosity,Log of GDP per capita,Healthy life expectancy
0,Finland,1,4,41.0,10.0,2.0,5.0,4.0,47.0,22.0,27.0
1,Denmark,2,13,24.0,26.0,4.0,6.0,3.0,22.0,14.0,23.0
2,Norway,3,8,16.0,29.0,3.0,3.0,8.0,11.0,7.0,12.0
3,Iceland,4,9,3.0,3.0,1.0,7.0,45.0,3.0,15.0,13.0
4,Netherlands,5,1,12.0,25.0,15.0,19.0,12.0,7.0,12.0,18.0

In [14]:
country_df = country_raw[['Country (region)','Ladder']]
country_df['Ladder'].astype(int)
country_df.head()

  Country (region)  Ladder
0          Finland       1
1          Denmark       2
2           Norway       3
3          Iceland       4
4      Netherlands       5

In [15]:
country_df = country_df.rename(columns={'Country (region)':'country','Ladder':'happiness'})
country_df.set_index('country')
country_df.head()

       country  happiness
0      Finland          1
1      Denmark          2
2       Norway          3
3      Iceland          4
4  Netherlands          5

In [16]:
temp_merge = pd.merge(starbucks_df, country_df, left_on = "country", right_on = "country", how="left")

temp_merge[['happiness']] = temp_merge[['happiness']].fillna(value = 0)
temp_merge

,id,brand,store_name,ownership_type,address,city,state,country,happiness
0,47370257954,Starbucks,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,Andorra,0.0
1,47089256771,Starbucks,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,United Arab Emirates,21.0
2,22126218024,Starbucks,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,United Arab Emirates,21.0
3,17127178586,Starbucks,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,United Arab Emirates,21.0
4,17688182164,Starbucks,"Dalma Mall, Ground Floor",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,United Arab Emirates,21.0
5,18182182165,Starbucks,"Dalma Mall, Level 1",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,United Arab Emirates,21.0
6,23359229184,Starbucks,Debenhams Yas Mall,Licensed,Yas Island,Abu Dhabi,AZ,United Arab Emirates,21.0
7,3078199022,Starbucks,Khalidiya Street,Licensed,Khalidiya St.,Abu Dhabi,AZ,United Arab Emirates,21.0
8,20423205465,Starbucks,Eastern Mangroves,Licensed,"Al Salam Street, The Mangroves",Abu Dhabi,AZ,United Arab Emirates,21.0
9,20424205466,Starbucks,Nation Towers,Licensed,Corniche Street,Abu Dhabi,AZ,United Arab Emirates,21.0
10,1579122101,Starbucks,HCT Abu Dhabi Women's College Block,Licensed,"Najda Street, Higher Colleges of Technology",Abu Dhabi,AZ,United Arab Emirates,21.0
11,32595122105,Starbucks,Standard Chartered Building,Licensed,"Khalidiya St., Beside Union Cooperative Society",Abu Dhabi,AZ,United Arab Emirates,21.0
12,24191236428,Starbucks,International Tower,Licensed,"Capital Center, Adnec, Abu Dhabi",Abu Dhabi,AZ,United Arab Emirates,21.0
13,24604238367,Starbucks,Yas Mall 3,Licensed,YAS Island,Abu Dhabi,AZ,United Arab Emirates,21.0
14,32029110804,Starbucks,Blue Tower A,Licensed,"Street No.4, Muroor Road, Ground Floor",Abu Dhabi,AZ,United Arab Emirates,21.0
15,29560238539,Starbucks,Corniche Park DT,Licensed,"Corniche Road , Abu Dhabi",Abu Dhabi,AZ,United Arab Emirates,21.0
16,32239100001,Starbucks,Khalidiya Mall,Licensed,"Street No.26 of Khalidiya Area, Ground Floor, ...",Abu Dhabi,AZ,United Arab Emirates,21.0
17,31719103601,Starbucks,Al Wahda Mall,Licensed,"11th Street, Ground Floor, Main Entrance",Abu Dhabi,AZ,United Arab Emirates,21.0
18,20008200004,Starbucks,Al Seef Village,Licensed,"Salam Street, Ministries District",Abu Dhabi,AZ,United Arab Emirates,21.0
19,32767131566,Starbucks,Shangri-La Souq,Licensed,"Shangri-La Souk, Um Al Nar",Abu Dhabi,AZ,United Arab Emirates,21.0
20,3886141408,Starbucks,"Abu Dhabi University, Men's",Licensed,"Muroor Street, Abu Dhabi Mall",Abu Dhabi,AZ,United Arab Emirates,21.0
21,29539254261,Starbucks,MUshrif Mall 1,Licensed,"25th st, Airport Road",Abu Dhabi,AZ,United Arab Emirates,21.0
22,28809251348,Starbucks,Boutik Mall Sun & Sky,Licensed,"Shams Abu Dhabi, Al Reem Island",Abu Dhabi,AZ,United Arab Emirates,21.0
23,3426262540,Starbucks,Marina Mall,Licensed,Marina Mall,Abu Dhabi,AZ,United Arab Emirates,21.0
24,3178141407,Starbucks,"Abu Dhabi University, Women's",Licensed,"Road Al Ain Abu Dhabi Road Number 22, Women Side",Abu Dhabi,AZ,United Arab Emirates,21.0
25,3426017877,Starbucks,Hamdan Street,Licensed,Hamdan Street,Abu Dhabi,AZ,United Arab Emirates,21.0
26,21605213406,Starbucks,Saadiyat Island,Licensed,Saadiyat Island,Abu Dhabi,AZ,United Arab Emirates,21.0
27,1935141406,Starbucks,Camellia Flowers,Licensed,"Khalidiya Area Khalidiya street, Behind Union ...",Abu Dhabi,AZ,United Arab Emirates,21.0
28,20113195784,Starbucks,Deerfields,Licensed,"Sheikh Zayed Road, Al Bahia Area",Abu Dhabi,AZ,United Arab Emirates,21.0
29,3422733225,Starbucks,Abu Dhabi Mall,Licensed,"Al Salam Street, Tourist Club Area",Abu Dhabi,AZ,United Arab Emirates,21.0
...,...,...,...,...,...,...,...,...,...
25568,10849103163,Starbucks,I-80 & Dewar Dr-Rock Springs,Company Owned,118 Westland Way,Rock Springs,WY,United States,19.0
25569,10769102454,Starbucks,Coffeen & Brundage Lane-Sheridan,Company Owned,2208 Coffeen Ave,Sheridian,WY,United States,19.0
25570,48482263452,Starbucks,Phạm Ngọc Thạch,Licensed,"2 Phạm Ngọc Thạch, Quận Đống Đa",Hà Nội,HN,Viet Nam,0.0
25571,24015232287,Starbucks,Press Club,Licensed,"59A Lý Thái Tổ, Quận Hoàn Kiếm, #123 Tầng trệt...",Hà Nội,HN,Viet Nam,0.0
25572,24016230012,Starbucks,IPH,Licensed,"241 Xuân Thủy, Quận Cầu Giấy",Hà Nội,HN,Viet Nam,0.0
25573,47910260386,Starbucks,The Garden,Licensed,"Tầng 1, TTTM The Garden, khu đô thị The Manor,...",Hà Nội,HN,Viet Nam,0.0
25574,24003228944,Starbucks,Lan Viên,Licensed,"32 Hàng Bài, Quận Hoàn Kiếm",Hà Nội,HN,Viet Nam,0.0
25575,24014231244,Starbucks,Bà Triệu,Licensed,"314 Bà Triệu, Quận Hai Bà Trưng",Hà Nội,HN,Viet Nam,0.0
25576,49436269127,Starbucks,The Vista,Licensed,"628 Xa Lo Ha Noi Highway, Dist 2, Ground Floor...",Ho Chi Minh,SG,Viet Nam,0.0
25577,49441269128,Starbucks,Ibis building,Licensed,"2 Hong Ha st, Ward 2, Tan Binh Dist, Tầng trệt...",Ho Chi Minh,SG,Viet Nam,0.0
25578,18663190626,Starbucks,President Place,Licensed,"93 Nguyễn Du, Quận 1, Tầng trệt Trung Tâm Thươ...",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25579,24011230014,Starbucks,Pandora,Licensed,"1/1 Trường Chinh, Quận Tân Phú",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25580,23633223885,Starbucks,Đông Du,Licensed,"38 Đông Du, Quận 1",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25581,23925226964,Starbucks,Đề Thám,Licensed,"191 - 193 Đề Thám, Quận 1",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25582,48282262438,Starbucks,Nguyễn Văn Trỗi,Licensed,"66 Nguyễn Văn Trỗi, Quận Phú Nhuận, Tầng trệt,...",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25583,25378234124,Starbucks,VivoCity,Licensed,"1058 Nguyễn Văn Linh, Quận 7",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25584,29695254869,Starbucks,Lakai,Licensed,"98-126 Nguyễn Tri Phương, Quận 5",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25585,48731264926,Starbucks,Thành Phố Hồ Chí Minh,Licensed,"Sân bay Tân Sơn Nhất, 45 Trường Sơn, Tân Bì...",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25586,25865242710,Starbucks,Kumho,Licensed,"39 Lê Duẩn, Quận 1",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25587,24009223886,Starbucks,Phan Xich Long,Licensed,"214 -216 Phan Xích Long, Quận Phú Nhuận",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25588,25346240592,Starbucks,Thảo Điền,Licensed,"21 Thảo Điền, Quận 2",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25589,29047252265,Starbucks,Nguyễn Huệ,Licensed,"99 Nguyễn Huệ, Quận 1",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25590,27767248666,Starbucks,SSG,Licensed,"561A Điện Biên Phủ, Quận Bình Thạnh, Khách sạn...",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25591,18687193924,Starbucks,New World,Licensed,"76 Lê Lai, Quận 1, Góc đường Phạm Hồng Thái và...",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25592,27082246744,Starbucks,Emart,Licensed,"168 Phan Văn Trị, Quận Gò Vấp, Khách sạn Rex",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25593,21401212072,Starbucks,Rex,Licensed,"141 Nguyễn Huệ, Quận 1, Góc đường Pasteur và L...",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25594,24010226985,Starbucks,Panorama,Licensed,"SN-44, Tòa Nhà Panorama, 208 Trần Văn Trà, Quận 7",Thành Phố Hồ Chí Minh,SG,Viet Nam,0.0
25595,47608253804,Starbucks,Rosebank Mall,Licensed,"Cnr Tyrwhitt and Cradock Avenue, Rosebank",Johannesburg,GT,South Africa,106.0
25596,47640253809,Starbucks,Menlyn Maine,Licensed,"Shop 61B, Central Square, Cnr Aramist & Coroba...",Menlyn,GT,South Africa,106.0
25597,47609253286,Starbucks,Mall of Africa,Licensed,"Shop 2077, Upper Level, Waterfall City",Midrand,GT,South Africa,106.0

In [17]:
temp = temp_merge[temp_merge.happiness == 0]
temp.head()

,id,brand,store_name,ownership_type,address,city,state,country,happiness
0,47370257954,Starbucks,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,Andorra,0.0
292,15476160864,Starbucks,Paseo Herencia,Licensed,J.E. Irausquin Blvd 382A,Noord,AW,Aruba,0.0
293,3635146029,Starbucks,Renaissance Seaport Marketplace,Licensed,L.G.Smith Blvd. 9,Oranjestad,AW,Aruba,0.0
294,3634146030,Starbucks,Renaissance Mall - Aruba,Licensed,L.G. Smith Boulevard 82,Oranjestad,AW,Aruba,0.0
344,26078242484,Starbucks,KUALA BELAIT,Licensed,"LOT 5354, KG. PANDAN KUALA BELAIT, BRUNEI DARU...",Brunei,BE,Brunei Darussalam,0.0

In [18]:
temp['country'].unique().tolist()

['Andorra',
 'Aruba',
 'Brunei Darussalam',
 'Bolivia, Plurinational State of',
 'Bahamas',
 'Curaçao',
 'Czechia',
 'Korea, Republic of',
 'Monaco',
 'Oman',
 'Puerto Rico',
 'Russian Federation',
 'Taiwan, Province of China',
 'Viet Nam']

In [19]:
starbucks_df['country'] = starbucks_df['country'].replace({'Bolivia, Plurinational State of':'Bolivia',
                                                           'Czechia':'Czech Republic',
                                                           'Korea, Republic of':'South Korea',
                                                           'Russian Federation':'Russia',
                                                           'Taiwan, Province of China':'Taiwan',
                                                           'Viet Nam':'Vietnam'})

In [20]:
starbucks_df

,id,brand,store_name,ownership_type,address,city,state,country
0,47370257954,Starbucks,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,Andorra
1,47089256771,Starbucks,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,United Arab Emirates
2,22126218024,Starbucks,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,United Arab Emirates
3,17127178586,Starbucks,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,United Arab Emirates
4,17688182164,Starbucks,"Dalma Mall, Ground Floor",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,United Arab Emirates
5,18182182165,Starbucks,"Dalma Mall, Level 1",Licensed,"Dalma Mall, Mussafah",Abu Dhabi,AZ,United Arab Emirates
6,23359229184,Starbucks,Debenhams Yas Mall,Licensed,Yas Island,Abu Dhabi,AZ,United Arab Emirates
7,3078199022,Starbucks,Khalidiya Street,Licensed,Khalidiya St.,Abu Dhabi,AZ,United Arab Emirates
8,20423205465,Starbucks,Eastern Mangroves,Licensed,"Al Salam Street, The Mangroves",Abu Dhabi,AZ,United Arab Emirates
9,20424205466,Starbucks,Nation Towers,Licensed,Corniche Street,Abu Dhabi,AZ,United Arab Emirates
10,1579122101,Starbucks,HCT Abu Dhabi Women's College Block,Licensed,"Najda Street, Higher Colleges of Technology",Abu Dhabi,AZ,United Arab Emirates
11,32595122105,Starbucks,Standard Chartered Building,Licensed,"Khalidiya St., Beside Union Cooperative Society",Abu Dhabi,AZ,United Arab Emirates
12,24191236428,Starbucks,International Tower,Licensed,"Capital Center, Adnec, Abu Dhabi",Abu Dhabi,AZ,United Arab Emirates
13,24604238367,Starbucks,Yas Mall 3,Licensed,YAS Island,Abu Dhabi,AZ,United Arab Emirates
14,32029110804,Starbucks,Blue Tower A,Licensed,"Street No.4, Muroor Road, Ground Floor",Abu Dhabi,AZ,United Arab Emirates
15,29560238539,Starbucks,Corniche Park DT,Licensed,"Corniche Road , Abu Dhabi",Abu Dhabi,AZ,United Arab Emirates
16,32239100001,Starbucks,Khalidiya Mall,Licensed,"Street No.26 of Khalidiya Area, Ground Floor, ...",Abu Dhabi,AZ,United Arab Emirates
17,31719103601,Starbucks,Al Wahda Mall,Licensed,"11th Street, Ground Floor, Main Entrance",Abu Dhabi,AZ,United Arab Emirates
18,20008200004,Starbucks,Al Seef Village,Licensed,"Salam Street, Ministries District",Abu Dhabi,AZ,United Arab Emirates
19,32767131566,Starbucks,Shangri-La Souq,Licensed,"Shangri-La Souk, Um Al Nar",Abu Dhabi,AZ,United Arab Emirates
20,3886141408,Starbucks,"Abu Dhabi University, Men's",Licensed,"Muroor Street, Abu Dhabi Mall",Abu Dhabi,AZ,United Arab Emirates
21,29539254261,Starbucks,MUshrif Mall 1,Licensed,"25th st, Airport Road",Abu Dhabi,AZ,United Arab Emirates
22,28809251348,Starbucks,Boutik Mall Sun & Sky,Licensed,"Shams Abu Dhabi, Al Reem Island",Abu Dhabi,AZ,United Arab Emirates
23,3426262540,Starbucks,Marina Mall,Licensed,Marina Mall,Abu Dhabi,AZ,United Arab Emirates
24,3178141407,Starbucks,"Abu Dhabi University, Women's",Licensed,"Road Al Ain Abu Dhabi Road Number 22, Women Side",Abu Dhabi,AZ,United Arab Emirates
25,3426017877,Starbucks,Hamdan Street,Licensed,Hamdan Street,Abu Dhabi,AZ,United Arab Emirates
26,21605213406,Starbucks,Saadiyat Island,Licensed,Saadiyat Island,Abu Dhabi,AZ,United Arab Emirates
27,1935141406,Starbucks,Camellia Flowers,Licensed,"Khalidiya Area Khalidiya street, Behind Union ...",Abu Dhabi,AZ,United Arab Emirates
28,20113195784,Starbucks,Deerfields,Licensed,"Sheikh Zayed Road, Al Bahia Area",Abu Dhabi,AZ,United Arab Emirates
29,3422733225,Starbucks,Abu Dhabi Mall,Licensed,"Al Salam Street, Tourist Club Area",Abu Dhabi,AZ,United Arab Emirates
...,...,...,...,...,...,...,...,...
25568,10849103163,Starbucks,I-80 & Dewar Dr-Rock Springs,Company Owned,118 Westland Way,Rock Springs,WY,United States
25569,10769102454,Starbucks,Coffeen & Brundage Lane-Sheridan,Company Owned,2208 Coffeen Ave,Sheridian,WY,United States
25570,48482263452,Starbucks,Phạm Ngọc Thạch,Licensed,"2 Phạm Ngọc Thạch, Quận Đống Đa",Hà Nội,HN,Vietnam
25571,24015232287,Starbucks,Press Club,Licensed,"59A Lý Thái Tổ, Quận Hoàn Kiếm, #123 Tầng trệt...",Hà Nội,HN,Vietnam
25572,24016230012,Starbucks,IPH,Licensed,"241 Xuân Thủy, Quận Cầu Giấy",Hà Nội,HN,Vietnam
25573,47910260386,Starbucks,The Garden,Licensed,"Tầng 1, TTTM The Garden, khu đô thị The Manor,...",Hà Nội,HN,Vietnam
25574,24003228944,Starbucks,Lan Viên,Licensed,"32 Hàng Bài, Quận Hoàn Kiếm",Hà Nội,HN,Vietnam
25575,24014231244,Starbucks,Bà Triệu,Licensed,"314 Bà Triệu, Quận Hai Bà Trưng",Hà Nội,HN,Vietnam
25576,49436269127,Starbucks,The Vista,Licensed,"628 Xa Lo Ha Noi Highway, Dist 2, Ground Floor...",Ho Chi Minh,SG,Vietnam
25577,49441269128,Starbucks,Ibis building,Licensed,"2 Hong Ha st, Ward 2, Tan Binh Dist, Tầng trệt...",Ho Chi Minh,SG,Vietnam
25578,18663190626,Starbucks,President Place,Licensed,"93 Nguyễn Du, Quận 1, Tầng trệt Trung Tâm Thươ...",Thành Phố Hồ Chí Minh,SG,Vietnam
25579,24011230014,Starbucks,Pandora,Licensed,"1/1 Trường Chinh, Quận Tân Phú",Thành Phố Hồ Chí Minh,SG,Vietnam
25580,23633223885,Starbucks,Đông Du,Licensed,"38 Đông Du, Quận 1",Thành Phố Hồ Chí Minh,SG,Vietnam
25581,23925226964,Starbucks,Đề Thám,Licensed,"191 - 193 Đề Thám, Quận 1",Thành Phố Hồ Chí Minh,SG,Vietnam
25582,48282262438,Starbucks,Nguyễn Văn Trỗi,Licensed,"66 Nguyễn Văn Trỗi, Quận Phú Nhuận, Tầng trệt,...",Thành Phố Hồ Chí Minh,SG,Vietnam
25583,25378234124,Starbucks,VivoCity,Licensed,"1058 Nguyễn Văn Linh, Quận 7",Thành Phố Hồ Chí Minh,SG,Vietnam
25584,29695254869,Starbucks,Lakai,Licensed,"98-126 Nguyễn Tri Phương, Quận 5",Thành Phố Hồ Chí Minh,SG,Vietnam
25585,48731264926,Starbucks,Thành Phố Hồ Chí Minh,Licensed,"Sân bay Tân Sơn Nhất, 45 Trường Sơn, Tân Bì...",Thành Phố Hồ Chí Minh,SG,Vietnam
25586,25865242710,Starbucks,Kumho,Licensed,"39 Lê Duẩn, Quận 1",Thành Phố Hồ Chí Minh,SG,Vietnam
25587,24009223886,Starbucks,Phan Xich Long,Licensed,"214 -216 Phan Xích Long, Quận Phú Nhuận",Thành Phố Hồ Chí Minh,SG,Vietnam
25588,25346240592,Starbucks,Thảo Điền,Licensed,"21 Thảo Điền, Quận 2",Thành Phố Hồ Chí Minh,SG,Vietnam
25589,29047252265,Starbucks,Nguyễn Huệ,Licensed,"99 Nguyễn Huệ, Quận 1",Thành Phố Hồ Chí Minh,SG,Vietnam
25590,27767248666,Starbucks,SSG,Licensed,"561A Điện Biên Phủ, Quận Bình Thạnh, Khách sạn...",Thành Phố Hồ Chí Minh,SG,Vietnam
25591,18687193924,Starbucks,New World,Licensed,"76 Lê Lai, Quận 1, Góc đường Phạm Hồng Thái và...",Thành Phố Hồ Chí Minh,SG,Vietnam
25592,27082246744,Starbucks,Emart,Licensed,"168 Phan Văn Trị, Quận Gò Vấp, Khách sạn Rex",Thành Phố Hồ Chí Minh,SG,Vietnam
25593,21401212072,Starbucks,Rex,Licensed,"141 Nguyễn Huệ, Quận 1, Góc đường Pasteur và L...",Thành Phố Hồ Chí Minh,SG,Vietnam
25594,24010226985,Starbucks,Panorama,Licensed,"SN-44, Tòa Nhà Panorama, 208 Trần Văn Trà, Quận 7",Thành Phố Hồ Chí Minh,SG,Vietnam
25595,47608253804,Starbucks,Rosebank Mall,Licensed,"Cnr Tyrwhitt and Cradock Avenue, Rosebank",Johannesburg,GT,South Africa
25596,47640253809,Starbucks,Menlyn Maine,Licensed,"Shop 61B, Central Square, Cnr Aramist & Coroba...",Menlyn,GT,South Africa
25597,47609253286,Starbucks,Mall of Africa,Licensed,"Shop 2077, Upper Level, Waterfall City",Midrand,GT,South Africa

# Connect to local database

In [ ]:
username=input("Enter User Name    ")

In [ ]:
password=getpass("Enter Password :")

In [ ]:
engine = create_engine(f'postgresql://{username}:{password}@localhost:5432/Starbucks_Happiness_db')
connection = engine.connect()

In [ ]:
 engine.table_names()

In [ ]:
starbucks_df.to_sql(name='starbucks', con = engine, if_exists='append', index=False)

In [ ]:
country_df.to_sql(name='happiness', con=engine, if_exists='append', index=False)

# Confirm data has been added by querying the starbucks table

In [ ]:
pd.read_sql_query('select * from starbucks', con=engine).head()

# Confirm data has been added by querying the happiness table

In [ ]:
pd.read_sql_query('select * from happiness', con=engine).head()